# Generated by Django 3.0.6 on 2020-06-01 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_deal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='chat.Contact', verbose_name='Партнер'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='chat.Contact', verbose_name='Юзер'),
        ),
    ]
