# Generated by Django 3.0.6 on 2020-06-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20200601_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='title',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
